# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "remotestate"
    key                  = "terraform.tfstate"
    resource_group_name  = "terratest-state"
    storage_account_name = "terratestremotestate"
  }
}
